import type { ReactNode } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { colors } from '@/constants/theme';
import { Icon } from './ui';

export function Screen({ children, scroll = true, keyboard = false, style }: { children: ReactNode; scroll?: boolean; keyboard?: boolean; style?: object }) { const body = scroll ? <ScrollView contentContainerStyle={[styles.content,style]} keyboardShouldPersistTaps="handled">{children}</ScrollView> : <View style={[styles.fill,style]}>{children}</View>; return <SafeAreaView style={styles.safe}>{keyboard ? <KeyboardAvoidingView style={styles.fill} behavior={Platform.select({ios:'padding',android:undefined})}>{body}</KeyboardAvoidingView> : body}</SafeAreaView>; }
export function Header({ title, subtitle, action, back = true }: { title:string; subtitle?:string; action?:ReactNode; back?:boolean }) { const router=useRouter(); return <View style={styles.header}>{back ? <Pressable accessibilityLabel="Go back" hitSlop={10} onPress={()=>router.back()} style={styles.back}><Icon name="chevron-back" /></Pressable> : <View style={styles.back}/>}<View style={styles.titleWrap}><Text style={styles.title} numberOfLines={1}>{title}</Text>{subtitle && <Text style={styles.subtitle} numberOfLines={1}>{subtitle}</Text>}</View>{action ?? <View style={styles.back}/>}</View> }
export function SectionTitle({children}:{children:ReactNode}) { return <Text style={styles.section}>{children}</Text> }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},fill:{flex:1},content:{paddingBottom:28},header:{height:60,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:12,borderBottomWidth:1,borderBottomColor:colors.border,backgroundColor:colors.background},back:{width:40,height:40,justifyContent:'center',alignItems:'center'},titleWrap:{flex:1},title:{fontSize:16,fontWeight:'800',color:colors.text},subtitle:{fontSize:12,color:colors.muted,marginTop:1},section:{fontSize:13,fontWeight:'800',color:colors.text,marginBottom:10} });
