import type { ComponentProps, ReactNode } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '@/constants/theme';

export const Icon = ({ name, size = 20, color = colors.primary }: { name: ComponentProps<typeof Ionicons>['name']; size?: number; color?: string }) => <Ionicons name={name} size={size} color={color} />;
export function Button({ title, onPress, variant = 'primary', disabled, loading, icon }: { title: string; onPress?: () => void; variant?: 'primary' | 'outline' | 'ghost' | 'danger'; disabled?: boolean; loading?: boolean; icon?: ComponentProps<typeof Ionicons>['name'] }) {
  const mode = variant === 'primary' ? styles.primary : variant === 'danger' ? styles.danger : variant === 'outline' ? styles.outline : styles.ghost;
  const label = variant === 'primary' ? styles.primaryText : variant === 'danger' ? styles.dangerText : styles.outlineText;
  return <Pressable accessibilityRole="button" disabled={disabled || loading} onPress={onPress} style={[styles.button, mode, (disabled || loading) && styles.disabled]}>{loading ? <ActivityIndicator color={variant === 'primary' ? '#fff' : colors.primary} /> : <>{icon && <Icon name={icon} size={18} color={variant === 'primary' ? '#fff' : variant === 'danger' ? colors.danger : colors.primary} />}<Text style={[styles.buttonText, label]}>{title}</Text></>}</Pressable>;
}
export function Input({ label, error, multiline, ...props }: ComponentProps<typeof TextInput> & { label?: string; error?: string }) { return <View style={styles.field}>{label && <Text style={styles.label}>{label}</Text>}<TextInput placeholderTextColor="#87938d" style={[styles.input, multiline && styles.multiline, error && styles.inputError]} multiline={multiline} {...props}/>{error && <Text style={styles.error}>{error}</Text>}</View>; }
export function Card({ children, style }: { children: ReactNode; style?: object }) { return <View style={[styles.card, style]}>{children}</View>; }
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'success'|'warning'|'info'|'danger'|'primary'|'neutral' }) { const tones = { success:[colors.success,'#e6f5ed'], warning:[colors.warning,colors.warningSoft], info:[colors.info,colors.infoSoft], danger:[colors.danger,colors.dangerSoft], primary:[colors.primary,colors.primarySoft], neutral:[colors.muted,'#f0f3f1'] } as const; const t=tones[tone]; return <View style={[styles.badge,{backgroundColor:t[1]}]}><View style={[styles.dot,{backgroundColor:t[0]}]}/><Text style={[styles.badgeText,{color:t[0]}]}>{children}</Text></View>; }
export function EmptyState({ icon='search-outline', title, description }: { icon?: ComponentProps<typeof Ionicons>['name']; title:string; description:string }) { return <View style={styles.empty}><View style={styles.emptyIcon}><Icon name={icon} size={25}/></View><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyText}>{description}</Text></View> }
const styles=StyleSheet.create({ button:{minHeight:48,borderRadius:24,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,paddingHorizontal:18},primary:{backgroundColor:colors.primary},outline:{backgroundColor:colors.card,borderWidth:1,borderColor:colors.border},ghost:{backgroundColor:'transparent'},danger:{backgroundColor:colors.dangerSoft,borderWidth:1,borderColor:'#f3c9c9'},disabled:{opacity:.48},buttonText:{fontSize:16,fontWeight:'700'},primaryText:{color:'#fff'},outlineText:{color:colors.primary},dangerText:{color:colors.danger},field:{gap:7},label:{fontSize:13,fontWeight:'700',color:colors.text},input:{minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:14,backgroundColor:colors.card,paddingHorizontal:14,fontSize:15,color:colors.text},multiline:{minHeight:88,paddingTop:12,textAlignVertical:'top'},inputError:{borderColor:colors.danger},error:{fontSize:12,color:colors.danger},card:{borderRadius:16,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,padding:14},badge:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:5,borderRadius:99,paddingHorizontal:8,paddingVertical:4},dot:{width:6,height:6,borderRadius:99},badgeText:{fontSize:11,fontWeight:'700'},empty:{alignItems:'center',padding:32,gap:8},emptyIcon:{width:52,height:52,borderRadius:26,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},emptyTitle:{fontSize:16,fontWeight:'700',color:colors.text},emptyText:{fontSize:13,color:colors.muted,textAlign:'center',lineHeight:19} });
