import type {
  Campaign,
  Conversation,
  Customer,
  NotificationItem,
  Order,
  Product,
  TeamMember,
  Template,
} from "./types"

export const shop = {
  name: "Sharma General Store",
  owner: "Rajesh Sharma",
  category: "Kirana Store",
  city: "Lucknow",
  state: "Uttar Pradesh",
  whatsappNumber: "+91 98765 43210",
  whatsappStatus: "connected" as const,
}

export const customers: Customer[] = [
  {
    id: "c1",
    name: "Anita Verma",
    phone: "+91 90123 45001",
    email: "anita.verma@example.com",
    tags: ["Regular", "VIP"],
    notes: "Prefers home delivery in the evening.",
    lastInteraction: "2 hours ago",
    orderCount: 18,
    totalSpend: 24560,
  },
  {
    id: "c2",
    name: "Suresh Patel",
    phone: "+91 90123 45002",
    tags: ["Wholesale"],
    lastInteraction: "Yesterday",
    orderCount: 32,
    totalSpend: 68900,
  },
  {
    id: "c3",
    name: "Priya Nair",
    phone: "+91 90123 45003",
    email: "priya.nair@example.com",
    tags: ["New"],
    lastInteraction: "3 days ago",
    orderCount: 1,
    totalSpend: 450,
  },
  {
    id: "c4",
    name: "Mohammed Iqbal",
    phone: "+91 90123 45004",
    tags: ["Regular"],
    lastInteraction: "5 days ago",
    orderCount: 9,
    totalSpend: 12300,
  },
  {
    id: "c5",
    name: "Deepika Rao",
    phone: "+91 90123 45005",
    tags: [],
    lastInteraction: "1 week ago",
    orderCount: 4,
    totalSpend: 3200,
  },
  {
    id: "c6",
    name: "Karan Malhotra",
    phone: "+91 90123 45006",
    tags: ["VIP"],
    lastInteraction: "2 weeks ago",
    orderCount: 22,
    totalSpend: 45200,
  },
]

export const products: Product[] = [
  {
    id: "p1",
    name: "India Gate Basmati Rice 5kg",
    sku: "RIC-5KG-001",
    category: "Grocery",
    price: 650,
    offerPrice: 599,
    stock: "in-stock",
    description: "Premium aged basmati rice, 5kg pack.",
    imageUrl: "/images/products/rice-bag.png",
  },
  {
    id: "p2",
    name: "Men's Cotton Kurta - Mustard",
    sku: "GRM-KRT-014",
    category: "Garments",
    price: 1299,
    offerPrice: 999,
    stock: "in-stock",
    description: "Pure cotton kurta, size M/L/XL available.",
    imageUrl: "/images/products/kurta.png",
  },
  {
    id: "p3",
    name: "Gold Plated Jhumka Earrings",
    sku: "JWL-ERG-102",
    category: "Jewellery",
    price: 2499,
    stock: "low-stock",
    description: "Traditional gold plated jhumka earrings.",
    imageUrl: "/images/products/earrings.png",
  },
  {
    id: "p4",
    name: "Galaxy Smart Phone 128GB",
    sku: "MOB-GLX-128",
    category: "Mobiles",
    price: 18999,
    offerPrice: 17499,
    stock: "in-stock",
    description: "128GB storage, 6GB RAM, dual camera.",
    imageUrl: "/images/products/smartphone.png",
  },
  {
    id: "p5",
    name: "750W Mixer Grinder",
    sku: "ELE-MXR-750",
    category: "Electronics",
    price: 3499,
    offerPrice: 2999,
    stock: "out-of-stock",
    description: "3 jars, 750W motor, 2 year warranty.",
    imageUrl: "/images/products/mixer.png",
  },
  {
    id: "p6",
    name: "8-Piece Hand Tool Kit",
    sku: "HRD-TLK-008",
    category: "Hardware",
    price: 899,
    stock: "in-stock",
    description: "Wrench, screwdriver set and pliers.",
    imageUrl: "/images/products/tools.png",
  },
]

export const conversations: Conversation[] = [
  {
    id: "conv1",
    customer: customers[0],
    lastMessage: "Kya aap kal delivery kar sakte hain?",
    time: "10:24 AM",
    unreadCount: 2,
    assignedStaff: "Rajesh",
    tags: ["Order"],
    messages: [
      { id: "m1", direction: "in", text: "Namaste! Rice available hai kya?", time: "10:10 AM" },
      { id: "m2", direction: "out", text: "Ha ji, available hai. 5kg pack 599 rupaye ka hai.", time: "10:12 AM", status: "read" },
      { id: "m3", direction: "in", text: "Theek hai, 2 bag bhej dena.", time: "10:20 AM" },
      { id: "m4", direction: "in", text: "Kya aap kal delivery kar sakte hain?", time: "10:24 AM" },
    ],
  },
  {
    id: "conv2",
    customer: customers[1],
    lastMessage: "Payment kar diya hai, screenshot bhej raha hoon",
    time: "9:45 AM",
    unreadCount: 0,
    assignedStaff: "Meena",
    tags: ["Wholesale", "Payment"],
    messages: [
      { id: "m1", direction: "in", text: "Order confirm kar do please", time: "9:30 AM" },
      { id: "m2", direction: "out", text: "Confirmed! Total amount 4500 hai.", time: "9:32 AM", status: "read" },
      { id: "m3", direction: "in", text: "Payment kar diya hai, screenshot bhej raha hoon", time: "9:45 AM" },
    ],
  },
  {
    id: "conv3",
    customer: customers[2],
    lastMessage: "Thank you! Order mil gaya",
    time: "Yesterday",
    unreadCount: 0,
    tags: ["New"],
    messages: [
      { id: "m1", direction: "out", text: "Aapka order deliver ho gaya hai.", time: "Yesterday", status: "delivered" },
      { id: "m2", direction: "in", text: "Thank you! Order mil gaya", time: "Yesterday" },
    ],
  },
  {
    id: "conv4",
    customer: customers[3],
    lastMessage: "Stock kab tak aayega mixer ka?",
    time: "Yesterday",
    unreadCount: 1,
    tags: ["Stock"],
    messages: [
      { id: "m1", direction: "in", text: "Stock kab tak aayega mixer ka?", time: "Yesterday" },
    ],
  },
  {
    id: "conv5",
    customer: customers[4],
    lastMessage: "Ok, samajh gaya",
    time: "2 days ago",
    unreadCount: 0,
    assignedStaff: "Rajesh",
    tags: [],
    messages: [
      { id: "m1", direction: "out", text: "Naya collection aa gaya hai, dekhna chahenge?", time: "2 days ago", status: "sent" },
      { id: "m2", direction: "in", text: "Ok, samajh gaya", time: "2 days ago" },
    ],
  },
]

export const orders: Order[] = [
  {
    id: "o1",
    number: "ORD-1042",
    customerId: "c1",
    customerName: "Anita Verma",
    items: [{ productId: "p1", name: "India Gate Basmati Rice 5kg", quantity: 2, price: 599 }],
    subtotal: 1198,
    total: 1198,
    status: "new",
    paymentStatus: "cod",
    deliveryMethod: "delivery",
    date: "Today, 10:20 AM",
  },
  {
    id: "o2",
    number: "ORD-1041",
    customerId: "c2",
    customerName: "Suresh Patel",
    items: [
      { productId: "p1", name: "India Gate Basmati Rice 5kg", quantity: 5, price: 599 },
      { productId: "p6", name: "8-Piece Hand Tool Kit", quantity: 2, price: 899 },
    ],
    subtotal: 4793,
    total: 4793,
    status: "processing",
    paymentStatus: "paid",
    deliveryMethod: "pickup",
    date: "Today, 9:32 AM",
  },
  {
    id: "o3",
    number: "ORD-1040",
    customerId: "c3",
    customerName: "Priya Nair",
    items: [{ productId: "p2", name: "Men's Cotton Kurta - Mustard", quantity: 1, price: 999 }],
    subtotal: 999,
    total: 999,
    status: "completed",
    paymentStatus: "paid",
    deliveryMethod: "delivery",
    date: "Yesterday, 4:10 PM",
  },
  {
    id: "o4",
    number: "ORD-1039",
    customerId: "c4",
    customerName: "Mohammed Iqbal",
    items: [{ productId: "p5", name: "750W Mixer Grinder", quantity: 1, price: 2999 }],
    subtotal: 2999,
    total: 2999,
    status: "cancelled",
    paymentStatus: "pending",
    deliveryMethod: "pickup",
    date: "Yesterday, 11:00 AM",
  },
  {
    id: "o5",
    number: "ORD-1038",
    customerId: "c6",
    customerName: "Karan Malhotra",
    items: [{ productId: "p4", name: "Galaxy Smart Phone 128GB", quantity: 1, price: 17499 }],
    subtotal: 17499,
    total: 17499,
    status: "completed",
    paymentStatus: "paid",
    deliveryMethod: "pickup",
    date: "2 days ago",
  },
]

export const templates: Template[] = [
  {
    id: "t1",
    name: "order_confirmation",
    category: "Utility",
    language: "English",
    status: "approved",
    body: "Hi {{1}}, your order {{2}} has been confirmed. Total: ₹{{3}}. Thank you for shopping with us!",
  },
  {
    id: "t2",
    name: "payment_reminder",
    category: "Utility",
    language: "Hindi",
    status: "approved",
    body: "Namaste {{1}}, aapka payment {{2}} abhi pending hai. Kripya jaldi bhej dein.",
  },
  {
    id: "t3",
    name: "diwali_offer_2025",
    category: "Marketing",
    language: "English",
    status: "pending",
    body: "🎉 Diwali Special! Flat 20% off on all products. Visit us today or reply to order.",
  },
  {
    id: "t4",
    name: "delivery_update",
    category: "Utility",
    language: "English",
    status: "approved",
    body: "Hi {{1}}, your order is out for delivery and will arrive today.",
  },
  {
    id: "t5",
    name: "flash_sale_weekend",
    category: "Marketing",
    language: "Hindi",
    status: "rejected",
    body: "Weekend sale! Sab kuch 50% off. Abhi call karein.",
  },
]

export const campaigns: Campaign[] = [
  {
    id: "cmp1",
    name: "Diwali Mega Sale",
    audience: "All customers (412)",
    template: "diwali_offer_2025",
    status: "scheduled",
    sent: 0,
    delivered: 0,
    read: 0,
    scheduledFor: "Oct 18, 9:00 AM",
  },
  {
    id: "cmp2",
    name: "Weekend Flash Sale",
    audience: "VIP customers (58)",
    template: "flash_sale_weekend",
    status: "completed",
    sent: 58,
    delivered: 56,
    read: 41,
  },
  {
    id: "cmp3",
    name: "New Stock Announcement",
    audience: "Regular customers (140)",
    template: "delivery_update",
    status: "running",
    sent: 140,
    delivered: 132,
    read: 78,
  },
  {
    id: "cmp4",
    name: "Winter Collection Launch",
    audience: "All customers (412)",
    template: "diwali_offer_2025",
    status: "draft",
    sent: 0,
    delivered: 0,
    read: 0,
  },
]

export const team: TeamMember[] = [
  { id: "tm1", name: "Rajesh Sharma", role: "Owner", status: "online", assignedChats: 3 },
  { id: "tm2", name: "Meena Kumari", role: "Manager", status: "online", assignedChats: 5 },
  { id: "tm3", name: "Vikram Singh", role: "Staff", status: "offline", assignedChats: 0 },
]

export const notifications: NotificationItem[] = [
  { id: "n1", title: "New WhatsApp Message", description: "Anita Verma sent a new message", time: "5 min ago", type: "message", read: false },
  { id: "n2", title: "New Order Received", description: "Order ORD-1042 from Anita Verma", time: "20 min ago", type: "order", read: false },
  { id: "n3", title: "Payment Received", description: "₹4,793 received from Suresh Patel", time: "1 hour ago", type: "payment", read: false },
  { id: "n4", title: "Campaign Completed", description: "Weekend Flash Sale reached 58 customers", time: "Yesterday", type: "campaign", read: true },
  { id: "n5", title: "WhatsApp Connection Issue", description: "Action required to keep messaging active", time: "2 days ago", type: "whatsapp", read: true },
]

export const homeMetrics = {
  todaysMessages: 47,
  unreadChats: 3,
  todaysOrders: 8,
  todaysSales: 12480,
}
